name: UPX Action
description: GitHub Action to run UPX on an executable

inputs:
  file:
    description: 'Input file'
  upx_args:
    description: 'Arguments to pass to UPX'

runs:
  using: docker
  image: Dockerfile
