name: 3rd-party

on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  goreportcard:
    name: Update state on goreportcard.com
    runs-on: ubuntu-20.04
    steps:
      - name: Send update request
        continue-on-error: true
        run: curl -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks

  godocs:
    name: Renew the documentation on pkg.go.dev
    runs-on: ubuntu-20.04
    steps:
      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@v1.0.1
